# Generated by Django 6.0 on 2026-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='points',
            field=models.IntegerField(),
        ),
    ]
